services:
  - type: cron
    name: scraper-batidoras
    repo: https://github.com/arturomontenegro/scraper-maquipan
    schedule: "@daily"
    plan: free
    dockerfilePath: Dockerfile
    envVars: []
